export const GET_MOVIES = "GET_MOVIES";
export const GET_PEOPLE = "GET_PEOPLE";
export const GET_TV = "GET_TV";
export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const LOG_IN = "LOG_IN";
// types related to registration and authentication process
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
// types related to errors
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
//types related to favouriting feature
export const GET_FAVOURITES = "GET_FAVOURITES";
export const ADD_FAVOURITE = "ADD_FAVOURITE";
export const DELETE_FAVOURITE = "DELETE_FAVOURITE";
export const FAVOURITES_LOADING = "FAVOURITES_LOADING";
